<a href="https://colab.research.google.com/github/manyasachdeva27/MACHINE-LEARNING/blob/main/Column_Tranformer_of_Scikit_learn_in_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('/content/covid_toy.csv')

In [4]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.transform(X_test[['fever']])

X_train_fever

array([[100.        ],
       [101.        ],
       [100.89189189],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [103.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [102.        ],
       [100.        ],
       [103.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [ 98

In [7]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [8]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[47],
       [38],
       [34],
       [12],
       [65],
       [31],
       [10],
       [15],
       [13],
       [65],
       [14],
       [34],
       [17],
       [73],
       [64],
       [49],
       [20],
       [74],
       [80],
       [48],
       [65],
       [83],
       [69],
       [72],
       [56],
       [34],
       [34],
       [82],
       [11],
       [18],
       [16],
       [65],
       [81],
       [26],
       [51],
       [19],
       [ 5],
       [71],
       [19],
       [75],
       [24],
       [11],
       [12],
       [23],
       [44],
       [19],
       [64],
       [20],
       [59],
       [42],
       [27],
       [80],
       [ 8],
       [23],
       [25],
       [47],
       [42],
       [68],
       [40],
       [16],
       [ 6],
       [60],
       [81],
       [20],
       [33],
       [82],
       [10],
       [55],
       [66],
       [69],
       [49],
       [42],
       [ 5],
       [46],
       [71],
       [51],
       [79],

In [9]:
# Ordinal Encoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])

X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        , 100.89189189,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 13.        , 100.        ,   0.        ,   0.        ,
          1.    

In [10]:
from sklearn.compose import ColumnTransformer

In [13]:
transformer=ColumnTransformer(transformers=[
                                            ('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(drop='first', sparse_output=False),['gender','city'])
                                            ],
                              remainder='passthrough')

In [15]:
X_train_transformed_ct = transformer.fit_transform(X_train)
X_test_transformed_ct = transformer.transform(X_test)